source 'https://api.berkshelf.com'

cookbook 'ohai'
cookbook 'git'
cookbook 'build-essential'
cookbook 'memcached'
cookbook 'nodejs'
cookbook 'database'
cookbook 'xml'
cookbook 'nginx'
cookbook 'imagemagick'
